### ISSUE TITLE
OAuth2 로그인 구현

### ISSUE THREAD

**Issue by kimgt0128** [kimgt0128/security-oauth2-JWT-honds-on-Spring-boot-3#2]
# 📌Feature Practice
>OAuth를 이용하여 기본 로그인 API를 설계합니다.
   

   

# 📝To-do
- [ ] 기본 프로젝트 설정
- [ ] 스프링 시큐리티를 이용하여 구글, 네이버, 카카오 로그인을 연동합니다.
- [ ] 간단한 유저 정보를 DB에 저장합니다.
- [ ] 기타 트러블 슈팅

   
# ✏️To-Study
- OAuth2의 Code Granted 방식을 사용하며 공부합니다.
- 간단한 방식을 적용하는 것보다 공부하는 것이 우선이므로 백엔드 전담 책임 방식으로 구현합니다.
- 백엔드 전담 책임 방식에 대해 신경써야할 보안 사항을 공부합니다.
